#############################
#        TO FILL            #
#############################

# The title that appears on the tab
title: Brennan Dai's Gallery

# The title on the web page
full_name: Brennan Dai

# The type of layout
# Options: ROWS, SQUARES, COLUMNS
layout_style: ROWS

# Variables below are default. Feel free to customize the values below, but do
# not remove the property.

# Integer: Spacing between each photo
spacing: 10

# Boolean(true|false): Shuffle the photos in the album
shuffle: false

# Integer: Number of columns for square or columns
columns: 4

# Integer: Max height for rows
max_height: 400

# Handle
instagram: andy.fuji

######################
# END OF CONFIG CODE #
#  Ignore below :)   #
######################
